# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 10.0
#     use_sim_time: True
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_navfn_planner/NavfnPlanner"
#       tolerance: 0.5
#       use_astar: false
#       allow_unknown: true
# global_costmap:
#   global_costmap:
#     ros__parameters:
#       update_frequency: 1.0
#       publish_frequency: 1.0
#       global_frame: map
#       robot_base_frame: base_link
#       use_sim_time: False
#       footprint: '[[0.3,0.5],[0.3,-0.5],[-0.3,-0.5],[-0.3,0.5]]'
#       resolution: 0.05
#       track_unknown_space: true
#       plugins: ["static_layer", "obstacle_layer", "voxel_layer","inflation_layer"]
#       filters: ["keepout_filter"]
#       #filters: ["speed_filter"]
#       static_layer:
#         plugin: "nav2_costmap_2d::StaticLayer"
#         map_subscribe_transient_local: True
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         enabled: True
#         observation_sources: scan
#         scan:
#           topic: /scan
#           max_obstacle_height: 2.0
#           clearing: True
#           marking: True
#           data_type: "LaserScan"
#           raytrace_max_range: 3.0
#           raytrace_min_range: 0.0
#           obstacle_max_range: 2.5
#           obstacle_min_range: 0.0
#       voxel_layer:
#           plugin: "nav2_costmap_2d::VoxelLayer"
#           enabled: True
#           footprint_clearing_enabled: true
#           max_obstacle_height: 2.0
#           publish_voxel_map: True
#           origin_z: 0.0
#           z_resolution: 0.05
#           z_voxels: 16
#           max_obstacle_height: 2.0
#           unknown_threshold: 15
#           mark_threshold: 0
#           observation_sources: pointcloud
#           combination_method: 1
#           pointcloud:  # no frame set, uses frame from message
#             topic: /point_cloud
#             max_obstacle_height: 2.0
#             min_obstacle_height: 0.0
#             obstacle_max_range: 2.5
#             obstacle_min_range: 0.0
#             raytrace_max_range: 3.0
#             raytrace_min_range: 0.0
#             clearing: True
#             marking: True
#             data_type: "PointCloud2"
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         cost_scaling_factor: 3.0
#         inflation_radius: 0.35
#       always_send_full_costmap: True
#       keepout_filter:
#         plugin: "nav2_costmap_2d::KeepoutFilter"
#         enabled: True
#         filter_info_topic: "/costmap_filter_info"
#       #speed_filter:
#         #plugin: "nav2_costmap_2d::SpeedFilter"
#         #enabled: True
#         #filter_info_topic: "/costmap_filter_info"
#         #speed_limit_topic: "/speed_limit"
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      # robot_radius: 1.0
      footprint: '[[0.6,0.9],[0.6,-0.9],[-0.6,-0.9],[-0.6,0.9]]'
      resolution: 0.05
      track_unknown_space: false # true
      plugins: ["static_layer", "obstacle_layer", "voxel_layer","inflation_layer"]
      filters: ["keepout_filter"]
      #filters: ["speed_filter"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      voxel_layer:
          plugin: "nav2_costmap_2d::VoxelLayer"
          enabled: True
          footprint_clearing_enabled: true
          max_obstacle_height: 2.0
          publish_voxel_map: True
          origin_z: 0.0
          z_resolution: 0.05
          z_voxels: 16
          max_obstacle_height: 2.0
          unknown_threshold: 15
          mark_threshold: 0
          observation_sources: pointcloud
          combination_method: 1
          pointcloud:  # no frame set, uses frame from message
            topic: /point_cloud
            max_obstacle_height: 2.0
            min_obstacle_height: 0.0
            obstacle_max_range: 2.5
            obstacle_min_range: 0.0
            raytrace_max_range: 3.0
            raytrace_min_range: 0.0
            clearing: True
            marking: True
            data_type: "PointCloud2"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5
        inflation_radius: 0.35
      always_send_full_costmap: True
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      #speed_filter:
        #plugin: "nav2_costmap_2d::SpeedFilter"
        #enabled: True
        #filter_info_topic: "/costmap_filter_info"
        #speed_limit_topic: "/speed_limit"